apiVersion: apps/v1
kind: Deployment  
metadata:
  name: backend-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: backend-app 
    spec:
      containers:
      - name: backend-app 
        image: shan20000/k8s_3teir_project:backend
        ports:
        - name: java
          containerPort: 8080
          protocol: TCP 
