apiVersion: v1
kind: Pod
metadata:
  name: myvolume-hostpath
spec:
  containers:
    - image: centos
      name: test
      command: ["/bin/bash", "-c", "sleep 15000"]
      volumeMounts:
        - mountPath: /tmp/hostpath
          name: testvolume
  volumes:
    - name: testvolume
      hostPath:
        path: /tmp/data


apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example
  labels:
    app: hostpath-demo
spec:
  containers:
  - name: hostpath-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo $(date) >> /mnt/hostpath/output.txt; sleep 50000; done"]
    volumeMounts:
    - mountPath: /mnt/hostpath
      name: hostpath-volume
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /data/hostpath
      type: DirectoryOrCreate
