apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: my-role
rules:
- apiGroup: [""]
  resource: ["Pods"]
  verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-rolebinding
subjects:
  - kind: User
    name: USERNAME-context
    apigroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: my-role 
  apiGroup: rbac.authorization.k8s.io