apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
spec:
  containers:
    - name: pod-with-secret
      image: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: my-credential
      ports: 
        - name: java
          containerPort: 3306
          protocol: TCP



[root@ip-172-31-46-163 kube]# kubectl get pod
NAME              READY   STATUS    RESTARTS   AGE
pod-with-secret   1/1     Running   0          35s
[root@ip-172-31-46-163 kube]# kubectl get pods -o wide
NAME              READY   STATUS    RESTARTS   AGE   IP            NODE       NOMINATED NODE   READINESS GATES
pod-with-secret   1/1     Running   0          45s   10.244.0.41   minikube   <none>           <none>
[root@ip-172-31-46-163 kube]# kubectl exec -it pod-with-secret -- env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=pod-with-secret
TERM=xterm
MYSQL_ROOT_PASSWORD=shan2003
KUBERNETES_SERVICE_HOST=10.96.0.1
MYPOD_SERVICE_HOST=10.99.28.38
MYPOD_PORT=tcp://10.99.28.38:80
MYPOD_PORT_80_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_PROTO=tcp
MYPOD_SERVICE_PORT=80
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
MYPOD_PORT_80_TCP_ADDR=10.99.28.38
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
MYPOD_PORT_80_TCP=tcp://10.99.28.38:80
MYPOD_PORT_80_TCP_PORT=80
GOSU_VERSION=1.17
LANG=C.UTF-8
MARIADB_VERSION=1:11.3.2+maria~ubu2204
HOME=/root
[root@ip-172-31-46-163 kube]